webtalk_init -webtalk_dir /home/centos/src/project_data/aws-fpga/hdk/cl/examples/cl_hello_world/verif/sim/vivado/test_null/xsim.dir/tb/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Feb 19 05:34:37 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.1_sdx_AR70350 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1933108" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "dddf4921-c843-46e5-9a07-7a16b45293ef" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c1d6f5b7-49a3-4114-b61b-d13adb707c98" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "CentOS" -context "user_environment"
webtalk_add_data -client project -key os_release -value "CentOS Linux release 7.4.1708 (Core)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E5-2666 v3 @ 2.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2893.442 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "31.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "5200 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1.94_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "234996_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2422437215 -regid "" -xml /home/centos/src/project_data/aws-fpga/hdk/cl/examples/cl_hello_world/verif/sim/vivado/test_null/xsim.dir/tb/webtalk/usage_statistics_ext_xsim.xml -html /home/centos/src/project_data/aws-fpga/hdk/cl/examples/cl_hello_world/verif/sim/vivado/test_null/xsim.dir/tb/webtalk/usage_statistics_ext_xsim.html -wdm /home/centos/src/project_data/aws-fpga/hdk/cl/examples/cl_hello_world/verif/sim/vivado/test_null/xsim.dir/tb/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
