# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2017.4.op
# Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
# 
# ==============================================================


/opt/Xilinx/Vivado/2017.4.op/bin/vivado  -notrace -mode batch -source ipi_example.tcl -tclargs xcvu9p-flgb2104-2-i ../xilinx_com_hls_vadd_1_0.zip
